# -*- coding: utf-8 -*-
"""P1_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pDmsAm3caU2oh74MKDovsgGAwHQA5-xr
"""

def can_king_move(x1, y1, x2, y2, checkerboard):

    if (x1, y1) == (x2, y2):
        return "No"


    dx = abs(x2 - x1)
    dy = abs(y2 - y1)


    if dx <= 1 and dy <= 1:

        if checkerboard[x2][y2] == 0:
            return "Yes"

    return "No"


x1, y1 = map(int, input().split())
x2, y2 = map(int, input().split())


print(can_king_move(x1, y1, x2, y2, checkerboard))